services:
  db:
    image: klishinoleg/cvosp/db:latest
    container_name: db
    networks:
      - database
    restart: always
    build:
      context: .
      dockerfile: ./docker/dpg.Dockerfile
    env_file: .env
    expose:
      - "${DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/entrypoint_db.sh:/usr/local/bin/db_entrypoint.sh
    entrypoint: [ "/usr/local/bin/db_entrypoint.sh" ]
  api:
    image: klishinoleg/cvosp/api:latest
    container_name: cvosp
    networks:
      - backend
      - database
    volumes:
      - ./fastapi:/cvosp
    build:
      context: ./fastapi
      dockerfile: ../docker/dapi.Dockerfile
    restart: always
    depends_on:
      - db
    expose:
      - "8000"
    env_file: .env
#  nginx:
#    image: nginx:latest
#    container_name: nginx
#    networks:
#      - backend
#      - frontend
#    env_file:
#      - path: .env
#        required: true
#    ports:
#      - "$SERVER_PORT:$SERVER_PORT"
#      - "$VITE_PORT:$VITE_PORT"
#    volumes:
#      - ./nginx/default.conf.template:/etc/nginx/conf.d/default.conf.template
#      - ./nginx/entrypoint.sh:/docker-entrypoint.d/99-entrypoint.sh
#    environment:
#      - SERVER_HOST=${SERVER_HOST}
#      - SERVER_PORT=${SERVER_PORT}
#      - VITE_HOST=${VITE_HOST}
#      - VITE_PORT=${VITE_PORT}
#    entrypoint: [ "/bin/sh", "-c", "/docker-entrypoint.d/99-entrypoint.sh && nginx -g 'daemon off;'" ]
#    depends_on:
#      - api
#      - vite
  vite:
    image: klishinoleg/cvosp/vite:latest
    container_name: vite
    networks:
      - frontend
    build:
      context: ./vite
      dockerfile: ../docker/dvite.Dockerfile
    env_file: .env
    environment:
      - SERVER_HOST=${SERVER_HOST}
      - SERVER_PORT=${SERVER_PORT}
      - VITE_HOST=${VITE_HOST}
      - LANGUAGE=${LANGUAGE}
      - LANGUAGES=${LANGUAGES}
      - HTTP_SCHEME=${HTTP_SCHEME}
    depends_on:
      - api
networks:
  frontend:
  backend:
  database:
volumes:
  postgres_data:
