services:
  db:
    image: postgres:15
    container_name: db
    restart: always
    env_file:
      - .env
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    volumes:
      - .:/cvosp
    build:
      context: .
      args:
        ADMIN_USER: ${ADMIN_USER}
        ADMIN_PASSWORD: ${ADMIN_PASSWORD}
        APP_PORT: ${APP_PORT}
        DB_PORT: ${DB_PORT}
    container_name: cvosp
    restart: always
    depends_on:
      - db
    env_file:
      - path: ".env"
        required: true
    ports:
      - "${APP_PORT}:${APP_PORT}"
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf.template:/etc/nginx/conf.d/default.conf.template
      - ./nginx/entrypoint.sh:/docker-entrypoint.d/99-entrypoint.sh
    environment:
      - APP_PORT=${APP_PORT}
    entrypoint: [ "/bin/sh", "-c", "/docker-entrypoint.d/99-entrypoint.sh && nginx -g 'daemon off;'" ]
    depends_on:
      - api
volumes:
  postgres_data:
